- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-pep8
    promote:
      jobs:
        - promote-openstack-contributor-guide
