[tox]
minversion = 4.28.0
envlist = docs,pep8
skipsdist = True

[testenv]
usedevelop = True
constraints =
  {env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}

[testenv:venv]
commands = {posargs}

[testenv:pep8]
deps =
  doc8>=0.6.0  # Apache-2.0
commands = doc8 -v doc README.rst

[testenv:docs]
deps =
  -r{toxinidir}/doc/requirements.txt
commands =
  docstheme-build-translated.sh
setenv =
  SPHINX_WARNINGS_TRANS=1

[doc8]
# Settings for doc8:
# Ignore build directory
ignore-path = doc/build/
# File extensions to use
extensions = .rst,.txt
